---
title: " "
output: 
  pdf_document:
    number_sections: TRUE
header-includes:
  - \usepackage{float}
  - \usepackage{sectsty}
  - \usepackage{setspace}
  - \setstretch{2.0}
  - \usepackage{ragged2e}
---

\doublespacing
\normalsize
\justifying


#	Chapter One
\vspace{-1em}
# Introduction{-}
\vspace{-1em}
##	Background of Study

|        The ability of workers to consume technology and adapt to emerging technology is quickly influencing the job market. The World Economic Forum (2023) estimates that by 2027, task automation in the global job market is likely to vary from 35% reasoning and decision-making to 65% information and processing by 2027. This is a clear indicator that data scientists are marketable. In a different publication, Vicario and Coleman (2018) mention that data scientists work in industries such as technology, production industries, e-commerce, and even agriculture. Clearly, the need for skilled personnel in data science is growing at an alarming rate, which has resulted in a lot of competition among giant companies in technology. This has led to innovations such as speech recognition (Siri) by apple, image detection by Google, and video recommendation from YouTube. Indeed, giant technology companies are consuming big data to create applications that are revolutionizing the world. These recent innovations prove that data science is growing rapidly and that the world is yet to see additional applications that will consume big data.

|        The big data era is fueled by gadgets that emit and store huge amounts of data. Examples of such gadgets include the smartphones, laptops, desktops, and IOT devices such as smart watches, and smart refrigerators. Owing to the recent increase in the amount of such data, people today store their extra data in the cloud and external hard drives but some people still store their data in gadgets that produce that data.  Critical to the discussion is the fact that smartphones have limited storage spaces implying that smartphone users at times extend their storage to the cloud. Additionally, the huge amount of storage space in smartphones is consumed by images and videos. These images and videos are mostly from social media while some of them come from pictures and videos recorded from smartphones. In short, smartphones produce a considerable amount of data that should be harnessed to make the world a better place.

|        Indeed, huge technology companies such as Google and Apple have developed world class applications that have enabled them to enjoy a competitive advantage over other companies.These data science applications (from Google and Apple) have been made possible by techniques such as support vector machines, random forests, decision trees, and neural networks. The term neural network refers to a connection of layers composed of units called perceptrons, which is made up of an input layer (the predictor variables), a processing unit, and an output layer (the response variable). The processing unit could comprise one or more hidden layers. That said, deep learning occurs when a neural network is created with more than one hidden layer. Having defined deep learning, it is imperative to highlight that decision trees and support vector machines were more famous than neural networks. However, the neural networks were brought to fame when Geoffrey Hinton et al., (2006) developed a neural network that predicted handwritten digits with an accuracy of 98%. 

|        Another field that emerged from deep learning is facial recognition. Lately, the field of facial recognition has attracted a lot of attention from scholars and practitioners. Some of the innovations that have emerged from facial recognition include development of home authentication systems, attendance management systems, security surveillance systems, and emotion recognition systems. Critical to the debate is the fact that different solutions of creating facial recognition systems have been proposed. One of the techniques that is used for facial recognition is convolution neural networks, which relies on hyper parameters like pooling, padding, strides, kernels, and the activation function. All these parameters affect the output of convolution neural networks differently. This is a clear indicator that studies examining how the mentioned hyper parameters affect the performance of convolution neural networks need to be discussed with an aim of developing a road map that could be used to train convolution neural networks.
	
##	Statement of the Problem

|        Researchers in facial recognition have developed solutions such as FaceNet, VGGFACE, VGG16, VGG19, OpenFace, and DeepFace. Even though existing solutions on facial recognition have been developed, the number of publications that investigate the effect of hyper parameter tuning on facial recognition are few. The publications become even fewer when the problem is narrowed down to convolution neural networks. Examples of hyper parameters that could be investigated under neural networks include padding, strides, filters, pooling, kernel size, the batch size, the learning rate and the number of layers. Critical to the debate is the fact that same padding, valid padding, causal padding and constant padding are some of the padding techniques used in deep learning. The most famous types of padding are valid and same padding. This begs the question: What would come out of examining the effect of padding on facial recognition? It is why this study aims to examine the effect of padding on facial recognition using data collected from smartphone images at Samasource.
	
##	Justification of the study

|        The justification of this study relies on the fact that convolution neural networks is the one stop shop when developing solutions in computer vision. Here, the term computer vision is defined as a facet in deep learning that develops solutions by analyzing images or videos. One of the important hyper parameters used in convolution neural networks is padding. Padding could be elucidated as a technique used to add data to an image’s borders, which results in the increase of the image’s height, width or depth. It is important to note that padding adds value in the training process of convolution because it could be used for dimension preservation or maintaining border information. Indeed, padding is an important hyper parameter used in training convolution neural networks because of the value it adds in the performance of a convolution neural network.

|        Given the role padding plays in training convolution neural networks, it is important to examine how different padding methods contribute to the performance of a convolution neural network. This owes to the reality it would help scholars and practitioners implement the right padding technique for the right problem. Moreover, it would be prudent to tell how padding affects the accuracy and training time of a model. This will help practitioners and scholars when making decisions that rely on the accuracy and training time of facial recognition models. Simply put, this publication will enable researchers to choose whether or not to implement padding when the training time of a model is of the essence. Likewise, it will aid scholars to make the decision of whether or not to implement padding when the accuracy of a facial recognition is the main goal of building the model.

##	OBJECTIVES OF THE STUDY

###	General Objectives

To examine the effect of padding on facial recognition using convolution neural networks and data collected using a smartphone.

### Specific Objectives

1.	To build a facial recognition model using convolution neural networks
2.	To examine the effect of padding on a pre-trained model: VGGFACE-16.
3.	To examine the effect of padding on facial recognition using a self-trained model
4.	To compare the effect of padding on VGGFACE-16 and a self-built model.
